# Generated by Django 4.0.2 on 2022-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pet_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bunny', 'Bunny'), ('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='publication_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
