# Generated by Django 4.0.2 on 2022-02-20 08:20

from django.db import migrations, models
import petstagram.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='mediafiles/media_files', validators=[petstagram.validators.validators.validate_image_size]),
        ),
    ]
