# Generated by Django 4.0.2 on 2022-03-19 11:45

from django.db import migrations, models
import django.db.models.deletion
import petstagram.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main_app', '0009_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='profiles', validators=[petstagram.validators.validators.validate_image_size]),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
